feat!: add exec command

diff --git a/domo b/domo
--- a/domo
+++ b/domo
@@ -25,6 +25,7 @@ domo_usage() {
   printf "  %s   Clone a remote git repository\n" "clone     "
   printf "  %s   Open a project\n" "open      "
   printf "  %s   List projects\n" "list      "
+  printf "  %s   Execute a command in a project\n" "exec      "
   echo
   printf "%s\n" "Commands:"
   printf "  %s   Space related commands\n" "space     "
@@ -181,6 +182,36 @@ domo_list_usage() {
     printf "%s\n" "Examples:"
     printf "  domo ls\n"
     printf "  domo list\n"
+    echo
+
+  fi
+}
+
+domo_exec_usage() {
+  printf "domo exec - Execute a command in a project\n\n"
+  printf "Alias: x\n"
+  echo
+
+  printf "%s\n" "Usage:"
+  printf "  domo exec COMMAND... [OPTIONS]\n"
+  printf "  domo exec --help | -h\n"
+  echo
+
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "Options:"
+
+    printf "  %s\n" "--path, -p PATH"
+    printf "    Path to the project\n"
+    echo
+
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    printf "%s\n" "Arguments:"
+
+    printf "  %s\n" "COMMAND..."
+    printf "    Command to execute in the project\n"
     echo
 
   fi
@@ -1172,7 +1203,8 @@ domo_open_command() {
   # Arguments
   #
 
-  local path="${args[path]}"
+  local path="${args[path]:-$(filter_projects)}"
+  [[ -z "${path}" ]] && exit 1
 
   #
   # Flags
@@ -1197,16 +1229,6 @@ domo_open_command() {
   #
   # PATH
   #
-
-  # If the path is not specified, use the filtered projects
-  if [[ -z "${path}" ]]; then
-      local path="${args[path]:-"$(filter_projects)"}"
-
-      if [[ -z "${path}" ]]; then
-          exit 1
-      fi
-  fi
-
   space="$(dirname "${path}")"
   name="$(basename "${path}")"
 
@@ -1233,6 +1255,33 @@ domo_open_command() {
 domo_list_command() {
 
   list_projects
+
+}
+
+domo_exec_command() {
+
+  #
+  # Arguments
+  #
+  local command="${args[command]}"
+
+  #
+  # Flags
+  #
+  local path="${args[--path]:-$(filter_projects)}"
+  [[ -z "${path}" ]] && exit 1
+
+  space="$(dirname "${path}")"
+  name="$(basename "${path}")"
+
+  if ! project_exists "${space}" "${name}"; then
+      error "no project '${name}' in space '${space}'"
+      exit 1
+  fi
+
+  cd "${DOMO_HOME}/${path}"
+
+  command ${command[@]}
 
 }
 
@@ -1283,8 +1332,6 @@ domo__uninstall_command() {
   # Arguments
   #
   local destination="${args[destination]}"
-
-  inspect_args
 
   #
   # Flags
@@ -1564,6 +1611,13 @@ parse_requirements() {
       action="list"
       shift
       domo_list_parse_requirements "$@"
+      shift $#
+      ;;
+
+    exec | x)
+      action="exec"
+      shift
+      domo_exec_parse_requirements "$@"
       shift $#
       ;;
 
@@ -1904,6 +1958,76 @@ domo_list_parse_requirements() {
 
     esac
   done
+
+}
+
+domo_exec_parse_requirements() {
+
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        domo_exec_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  action="exec"
+
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      --path | -p)
+
+        if [[ -n ${2+x} ]]; then
+          args['--path']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "$(error)--path requires an argument: --path, -p PATH" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "$(error)invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+
+        escaped="$(printf '%q' "$1")"
+        if [[ -z ${args['command']+x} ]]; then
+          args['command']="$escaped"
+        else
+          args['command']="${args['command']} $escaped"
+
+        fi
+        shift
+
+        ;;
+
+    esac
+  done
+
+  if [[ -z ${args['command']+x} ]]; then
+    printf "$(error)missing required argument: COMMAND\n" >&2
+
+    exit 1
+  fi
+
+  if [[ -v args['--path'] && -n $(validate_project_exists "${args['--path']:-}") ]]; then
+    printf "$(error)validation error in %s:\n%s\n" "--path, -p PATH" "$(validate_project_exists "${args['--path']:-}")" >&2
+    exit 1
+  fi
 
 }
 
@@ -3114,6 +3238,7 @@ run() {
     "clone") domo_clone_command ;;
     "open") domo_open_command ;;
     "list") domo_list_command ;;
+    "exec") domo_exec_command ;;
     "_install") domo__install_command ;;
     "_uninstall") domo__uninstall_command ;;
     "space") domo_space_command ;;
